name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format code with Black
        uses: psf/black@stable
        with:
          src: mujoco_utils/